/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.amazon.aocagent;

import com.amazon.aocagent.integtests.BasicIntegTest;

public class App {
    public static void main(String[] args) {
        new BasicIntegTest().execute();
    }
}
